app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include('posts.urls'))
]

posts/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='Home'),
    re_path('^search/<search_query>$', views.search_categories, name='Search'),
    re_path('^filer/<location_filter>$', views.search_categories, name='Filter Location'),
]

posts/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from .link_generator import generate_shareable_link

# Create your models here.
class Location(models.Model):
    name = models.CharField(max_length=255, default=None)

    def __str__(self):
        return self.name
    
class Category(models.Model):
    title = models.CharField(max_length=255, default=None)

    def __str__(self):
        return self.title

class Photo(models.Model):
    
    sharable_link = generate_shareable_link()
   
    title = models.CharField(max_length=255, default=None)
    description = models.TextField()
    location = models.ForeignKey(Location, on_delete=models.CASCADE,)
    category = models.ManyToManyField(Category)
    date = models.DateTimeField(auto_now=True)
    img_url = CloudinaryField('image', default=None)
    sharable_link = models.CharField(max_length=255, unique=True, default=sharable_link)

    def __str__(self):
        return self.title

posts/views.py
from django.shortcuts import render
from .models import Category, Location, Photo 
# Create your views here.
def index(request):
    title = "Home: Welcome to Story Book"
    allPosts = Photo.objects.all()
    
    return render(request, 'home.html', {"title":title ,"posts": allPosts})

def search_categories(request, search_query):
    title = f'Search: {search_query} Results'
    Photo.objects.filter(category = search_query)
    
    return render(request, 'search.html', {"title": title})

def filter_by_location(request, location_query):
    title=f'Posts from {location_query}'
    filtered_posts = Photo.objects.filter(location = location_query)
    
    return render(request, 'home.html', {"title": title, "posts": filtered_posts})

posts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Story Book Prototype</title>
    {% endif %}

    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />
  </head>
  <body id="body " onload="viewport_tracker()">
    <div id="main-container">
      <div class="sidebar-header">
        <button class="btn" id="menu-drawer" onclick="sidebar_toggle()">
          <i class="fas fa-bars"></i>
        </button>
      </div>
      <div id="sidebar">
        <div class="user-info-container">
          <a href="{% url 'posts:Home' %}">
            <img src="{% static 'images/logo.png' %}" alt="logo" class="logo" />
          </a>
        </div>
        <div class="user-bio-container">
          <p class="sidebar-label">About:</p>
          <p class="user-bio-text">
            Story Book is a photo-sharing app that aims to share visual tales as
            told through the lenses of a camera. <br /><br />

            As a user, you can view more information about the a post by
            clicking on the image. You can also go return to the home-page any
            time by clicking on the 'Story Book' logo above. Lastly, you can
            filter the posts by location below or search for a specific category
            through the search form at the top right corner (or under the navbar
            for mobile users)
          </p>
        </div>
        <div class="upload-button-container">
          <button class="upload-button">Filter</button>
        </div>
      </div>
      <div class="search-bar-container">
        <div class="search-bar-form">
          <form action="" class="search-form">
            <div class="input-group mb-3">
              <input
                type="text"
                class="form-control search-form-input"
                placeholder="Search..."
                aria-label="Search..."
                aria-describedby="button-addon2"
              />
              <div class="input-group-append">
                <button
                  class="btn search-form-button"
                  type="button"
                  id="button-addon2"
                >
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>

      <div id="content">{% block content %} {% endblock content %}</div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
      crossorigin="anonymous"
    ></script>

    <script src="{% static 'js/sidebar.js' %}"></script>

    <script
      src="https://kit.fontawesome.com/a872bbb5df.js"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

posts/templates/home.html
{% extends 'base.html' %}

<!-- start of content block -->
{% block content %}
<!-- start of if block -->
{% if posts %}
<!-- start of for loop -->
{% for post in posts %}

<div class="card photo-post-item">
  <button
    type="button"
    class="btn"
    data-toggle="modal"
    data-target="#post{{post.id}}"
  >
    <img
      class="card-img-top photo-post-img"
      src="{{post.img_url.url}}"
      alt=""
    />
  </button>
  <div class="card-body photo-post-body-container">
    <div class="Photo-text-container">
      <h4 class="card-title photo-post-title">{{post.title}}</h4>
      <p class="card-text photo-post-date">{{post.date}}</p>
    </div>
    <div class="photo-like-container">
      <button class="btn"></button>
    </div>
  </div>
</div>

<div
  class="modal fade"
  id="post{{post.id}}"
  tabindex="-1"
  aria-labelledby="{{post.id}}Label"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="post{{post.id}}Label">{{post.title}}</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body photo-post-modal">
        <div class="photo-post-img-container">
          <img
            src="{{post.img_url.url}}"
            alt=""
            class="photo-post-view w-100"
          />
        </div>
        <div class="photo-post-text-container">
          <p class="photo-post-location">{{post.title}}</p>
          <p class="photo-post-date mb-0">{{post.location.name}}</p>
          <p class="photo-post-date">{{post.date}}</p>
          <p class="photo-post-desc">{{post.description}}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %} {% else %}
<p class="search-sub-header-text text-dark text-center">
  There are no images uploaded.
  <br />Please try again later.
</p>
{% endif %} {% endblock %}

posts/templates/search.html
{% extends 'base.html' %}

<!-- start of content block -->
{% block content %}
<div class="search-header-container">
  <div class="search-header">
    <p class="search-header-text">Search Results for "Drone Shoots":</p>
  </div>
<!-- start of if block -->
{% if results %}

  <div class="search-header ">
    <p class="search-sub-header-text">{{results | length}} Images Found:</p>
  </div>
</div>
<div class="search-results-container">
  {% for post in results %}

  <div class="card photo-post-item">
    <button
      type="button"
      class="btn"
      data-toggle="modal"
      data-target="#{{post.id}}"
    >
      <img class="card-img-top photo-post-img" src="{{post.img_url}}" alt="" />
    </button>
    <div class="card-body photo-post-body-container">
      <div class="Photo-text-container">
        <h4 class="card-title photo-post-title">{{post.title}}</h4>
        <p class="card-text photo-post-date">{{post.date}}</p>
      </div>
      <div class="photo-like-container">
        <button class="btn"></button>
      </div>
    </div>
  </div>

  <div
    class="modal fade"
    id="{{post.id}}"
    tabindex="-1"
    aria-labelledby="{{post.id}}Label"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="{{post.id}}Label">{{post.title}}</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body photo-post-modal">
          <div class="photo-post-img-container">
            <img src="{{post.img_url}}" alt="" class="photo-post-view w-100" />
          </div>
          <div class="photo-post-text-container">
            <p class="photo-post-location">{{post.img_url}}</p>
            <p class="photo-post-date">{{post.date}}</p>
            <p class="photo-post-desc">{{post.description}}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% else %}


  <div class="search-header w-100">
    <p class="search-sub-header-text mt-3 mx-auto text-center">No Images Found</p>
  </div>
</div>
<div class="search-results-container"></div>
{% endif %} {% endblock content %}